
version: '3'
services:
  prometheus:
    image: prom/prometheus                   #install docker-compose plugin for that
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

