version: '3.8'

services:
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ~/alertmanager:/etc/alertmanager
    restart: unless-stopped
